apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2020-05-21T18:20:22Z"
  generation: 8
  labels:
    app: pushpin-backend
  name: pushpin-backend
  namespace: wso2
  resourceVersion: "52893294"
  selfLink: /apis/extensions/v1beta1/namespaces/wso2/deployments/pushpin-backend
  uid: b52891dd-dc28-4ed4-b49b-e4cfd03b3bda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pushpin-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2020-06-09T17:49:44+05:30"
      creationTimestamp: null
      labels:
        app: pushpin-backend
    spec:
      containers:
      - image: gharikrishna123/pushpinbackend:v5
        imagePullPolicy: Always
        name: pushpin-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockercred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: wso2svcacct
      serviceAccountName: wso2svcacct
      terminationGracePeriodSeconds: 90


---
apiVersion: v1
kind: Service
metadata:
  name: pushpin-backend-svc
  namespace: wso2
  selfLink: /api/v1/namespaces/wso2/services/pushpin-backend-svc
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http2
    port: 8090
    protocol: TCP
    targetPort: 8090 
  selector:
    app: pushpin-backend
  sessionAffinity: None
  type: ClusterIP
