apiVersion: v1
kind: Service
metadata:
  name: pushpin-public-svc
  namespace: wso2
spec:
  clusterIP: None
  ports:
  - name: http
    port: 7999
    targetPort: 7999
  selector:
    app: pushpin
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pushpin-private-svc
  namespace: wso2
spec:
  clusterIP: None
  ports:
  - name: http
      port: 7999
      targetPort: 7999
  - name: http1
      port: 5560
      targetPort: 5560
  - name: http2
      port: 5561
      targetPort: 5561
  - name: http3
      port: 5562
      targetPort: 5562
  - name: http4
      port: 5563
      targetPort: 5563  
  selector:
    app: pushpin
  sessionAffinity: None
---  
apiVersion: v1
kind: Service
metadata:
  name: pushpin-java-backend
  namespace: wso2
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: pushpin-java-backend
  sessionAffinity: None
  type: NodePort  