apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    metadata:
      name: init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - image: tmaier/postgresql-client
        name: init-db
        #command: ["sh","-c","sleep 500000"]
        command: [ "sh","-c","psql -h pg-service -p 5432 -f /sqlCommand/db-init.sql -U rtuser "]
        volumeMounts:
        - name: sql
          mountPath: /sqlCommand/
        env:
          - name: DB_HOST
            value: "pg-service"
          - name: DB_DATABASE
            value: "postgres" 
      volumes:
        - name: sql
          configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
            name: psql-apps-config
      restartPolicy: OnFailure