apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pushpin
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushpin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pushpin
    spec:
      serviceAccountName: wso2svcacct
      imagePullSecrets:
        - name: dockercred
      containers:
      - name: pushpin
        image: fanout/pushpin
        ports:
        - containerPort: 7999
        - containerPort: 5560
        - containerPort: 5561
        - containerPort: 5562
        - containerPort: 5563
        
      - name: pushpin-backend
        image: nnallapu/rt-connect:1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
        volumeMounts:
            - name: si-node-one
              mountPath: /siddhi-files/si-efs-one
            - name: si-node-two
              mountPath: /siddhi-files/si-efs-two
        
      volumes:
      - name: pushpin-config
        configMap:
           name: pushpin-config 
      - name: si-node-one
        persistentVolumeClaim:
          claimName: si-worker-1-volume-claim
      - name: si-node-two
        persistentVolumeClaim:
            claimName: si-worker-2-volume-claim        

       
---
apiVersion: v1
kind: Service
metadata:
  name: pushpin-svc
  namespace: wso2
spec:
  selector:
    app: pushpin
  clusterIP: None
  ports:
  - name: http
    port: 7999
    targetPort: 7999  
  - name: http1
    port: 5560
    targetPort: 5560  
  - name: http2
    port: 5561
    targetPort: 5561 
  - name: http3
    port: 5562
    targetPort: 5562  
  - name: http4
    port: 5563
    targetPort: 5563       
---