apiVersion: v1
data:
  db-install.sql: 
    CREATE TABLE pushpin_subscription(
    channel character varying COLLATE pg_catalog."default" NOT NULL,
    nodes character varying[] COLLATE pg_catalog."default",
    CONSTRAINT pushpin_subscription_pkey PRIMARY KEY (channel));
  db-uninstall.sql: 
    DROP table pushpin_subscription;

  db.install: 'true'
kind: ConfigMap
metadata:
  name: psql-script-config
  # namespace: wso2